{
 "title": "Step Functions - Gauges Proporcionais Compatíveis",
 "tags": [
  "stepfunctions",
  "gauge",
  "compat"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Total de Execuções",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message \n| parse @message /\"type\":\"(?<type>[^\"]+)\"/ \n| filter type like /Execution/  \n| stats count()",
     "logGroups": [
      {
       "accountId": "835996031136",
       "arn": "arn:aws:logs:us-east-1:835996031136:log-group:/aws/vendedlogs/states/SimpleStartStateMachine-Logs:*",
       "name": "/aws/vendedlogs/states/SimpleStartStateMachine-Logs"
      }
     ],
     "queryMode": "Logs",
     "region": "us-east-1"
    }
   ]
  },
  {
   "title": "Execuções com Sucesso",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message \n| parse @message /\"type\":\"(?<type>[^\"]+)\"/ \n| filter type = \"ExecutionSucceeded\" \n| stats count()",
     "logGroups": [
      {
       "accountId": "835996031136",
       "arn": "arn:aws:logs:us-east-1:835996031136:log-group:/aws/vendedlogs/states/SimpleStartStateMachine-Logs:*",
       "name": "/aws/vendedlogs/states/SimpleStartStateMachine-Logs"
      }
     ],
     "queryMode": "Logs",
     "region": "us-east-1"
    },
    {
     "expression": "fields @message | parse @message /\"type\":\"(?<type>[^\"]+)\"/ | filter type like /Execution/ | stats count()",
     "logGroups": [
      {
       "accountId": "835996031136",
       "arn": "arn:aws:logs:us-east-1:835996031136:log-group:/aws/vendedlogs/states/SimpleStartStateMachine-Logs:*",
       "name": "/aws/vendedlogs/states/SimpleStartStateMachine-Logs"
      }
     ],
     "queryMode": "Logs",
     "region": "us-east-1"
    }
   ]
  },
  {
   "title": "Execuções em Andamento",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message \n| parse @message /\"execution_arn\":\"(?<executionArn>[^\"]+)\"/ \n| parse @message /\"type\":\"(?<type>[^\"]+)\"/ \n| parse @message /\"event_timestamp\":\"(?<eventTime>\\d+)\"/ \n| stats latest(type) as lastType, max(eventTime) as lastEventTime by executionArn \n| filter lastType not in [\"ExecutionSucceeded\", \"ExecutionFailed\", \"ExecutionAborted\", \"ExecutionTimedOut\"] \n| stats count(*) as total\n",
     "logGroups": [
      {
       "accountId": "835996031136",
       "arn": "arn:aws:logs:us-east-1:835996031136:log-group:/aws/vendedlogs/states/SimpleStartStateMachine-Logs:*",
       "name": "/aws/vendedlogs/states/SimpleStartStateMachine-Logs"
      }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "executionArn" ]
    },
    {
     "expression": "fields @message | parse @message /\"type\":\"(?<type>[^\"]+)\"/ | filter type like /Execution/ | stats count()",
     "logGroups": [
      {
       "accountId": "835996031136",
       "arn": "arn:aws:logs:us-east-1:835996031136:log-group:/aws/vendedlogs/states/SimpleStartStateMachine-Logs:*",
       "name": "/aws/vendedlogs/states/SimpleStartStateMachine-Logs"
      }
     ],
     "queryMode": "Logs",
     "region": "us-east-1"
    }
   ]
  },
  {
   "title": "Execuções com Erro",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message \n| parse @message /\"type\":\"(?<type>[^\"]+)\"/ \n| filter type = \"ExecutionFailed\" \n| stats count()",
     "logGroups": [
      {
       "accountId": "835996031136",
       "arn": "arn:aws:logs:us-east-1:835996031136:log-group:/aws/vendedlogs/states/SimpleStartStateMachine-Logs:*",
       "name": "/aws/vendedlogs/states/SimpleStartStateMachine-Logs"
      }
     ],
     "queryMode": "Logs",
     "region": "us-east-1"
    },
    {
     "expression": "fields @message \n| parse @message /\"type\":\"(?<type>[^\"]+)\"/ \n| filter type like /Execution/ \n| stats count()",
     "logGroups": [
      {
       "accountId": "835996031136",
       "arn": "arn:aws:logs:us-east-1:835996031136:log-group:/aws/vendedlogs/states/SimpleStartStateMachine-Logs:*",
       "name": "/aws/vendedlogs/states/SimpleStartStateMachine-Logs"
      }
     ],
     "queryMode": "Logs",
     "region": "us-east-1"
    }
   ]
  }
 ]
}